modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/Prunoideae/ProbeJS"
license = "GPLv3"

[[mods]]
modId = "probejs"
version = "${version}"
displayName = "ProbeJS"
authors = "Prunoideae"
description = '''
Improving your KubeJS scripting experience by generating auto-completions of all kinds.
'''
logoFile = "icon.png"

[[dependencies.probejs]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.probejs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.probejs]]
modId = "architectury"
mandatory = true
versionRange = "[4.1.39,)"
ordering = "AFTER"
side = "BOTH"